BoxLayout:
	orientation: "vertical"
	canvas.before: 
		Color:
			rgba: rgba("FBFBFB")
		Rectangle:
			pos: self.pos
			size: self.size
	ColoredBox:
		orientation: "horizontal"
		ColoredBox:
			bg_color: 1,0,1,0
			size_hint: None, 1
			width: dp(16+24)
			padding: dp(16)
			ColoredBox:
				bg_color: 0,1,1,0
				size_hint: None, None
				pos_hint: {"center_y": 0.5}
				size: dp(24), dp(24)
				canvas.after: 
					Color:
						rgba: rgba("333333")
					Line:
						points: [self.pos[0]+dp(7), self.pos[1]+dp(6)+dp(12)+dp(8), self.pos[0]+dp(1), self.pos[1]+dp(6)+dp(6)+dp(8), self.pos[0]+dp(7), self.pos[1]+dp(6)+dp(8)]
						width: 1.2
		ColoredBox:
			bg_color: 0,0,1,0
		LabelB: 
			text: "Google LLC"
			font_name: "fonts//Roboto-Medium.ttf"
			color: rgba("333333")
			font_size: dp(22)
			pos_hint: None, None
			pos_hint: {'x': 0.5}
			halign: "center"
		ColoredBox:
			bg_color: 1,0,1,0
			size_hint: None, None
			size: ((((self.parent.size[0])-dp(16+24))/3) +((+dp(16)+dp(24))/2), self.parent.size[1])
	ColoredBox:
		bg_color: rgba("FFFFFF")
		size_hint: 1,None
		height: dp(714-34)
		orientation: "vertical"
		#logos_google-icon.png
		ColoredBox:
			bg_color: 1,0,0,1
		ColoredBox:
			bg_color: 0,1,0,1
		ColoredBox:
			bg_color: 0,0,1,1

<ColoredBox@BoxLayout>:
	bg_color: 1,1,1,1
	canvas.before: 
		Color:
			rgba: self.bg_color
		Rectangle:
			pos: self.pos
			size: self.size

<LabelB@Button>:
	background_normal: ''
    background_down: ''
    background_disabled_normal: ''
    background_disabled_down: ''
    background_color: 0, 0, 0, 0
